#ifndef __CLUNET_CONFIG_H__
#define __CLUNET_CONFIG_H__


#define CLUNET_READING_BUFFER_SIZE	128
#define CLUNET_SENDING_BUFFER_SIZE	128

#define CLUNET_DEVICE_ID		0x07
#define DEVICE_NAME_MAX_SIZE		16

// 16MHz / 64 / 16 = 15625 Hz
#define CLUNET_T		16

#define CLUNET_TIMER_REG	TIM6->CNT
#define CLUNET_TIMER_OCR	TIM6->ARR
#define CLUNET_TIMER_RESET_FLAG	TIM6->SR &= ~TIM_SR_UIF
#define CLUNET_TIMER_ENABLE	TIM6->CR1 |= TIM_CR1_CEN
#define CLUNET_TIMER_DISABLE	TIM6->CR1 &= (~((uint16_t)TIM_CR1_CEN))

#define CLUNET_READ			(!(GPIOB->IDR & 0x02))
#define CLUNET_PIN_INT_DISABLE	 	EXTI->IMR &=~(EXTI_IMR_MR1)
#define CLUNET_PIN_INT_ENABLE  		EXTI->IMR |=(EXTI_IMR_MR1)

#define CLUNET_OUT_SET0		GPIOB->ODR&=~0x04
#define CLUNET_OUT_SET1		GPIOB->ODR=0x04
#define CLUNET_OUT_TOGGLE	GPIOB->ODR^=0x04


#endif